server:
  port: 9000
  contextPath: /v2-api

solon.app:
  name: 'sra-solon-web'
#添加静态目录映射
solon.staticfiles.mappings:
  - path: "/download/" #路径，可以是目录或单文件
    repository: "D:/server/file/" #1.添加本地绝对目录（仓库只能是目录）

sqltoy:
  sqlResourcesDir: classpath:sqltoy
  unify-fields-handler: net.cocotea.admin.handler.SqlToyUnifyFieldsHandler


sra-admin:
  # 默认创建用户的密码
  password: SraAdmin123456
  # 密码加密的加盐
  password-salt: SraAdmin@salt
  # 开启缓存
  permission-cache: true
  # 是否开启系统日志保存功能
  save-log: true
  # 强密码，为空或者为none表示关闭
  strong-password: none
  # 1秒内访问服务器接口频率
  once-visits: 30
  # 路由放行（用逗号分割）
  excludes: /system/dashboard/index,/system/login,/system/captcha,/,/doc/**
  # 文件存放配置
  file:
    # 默认文件存放位置
    default-path: F:/Files/default/
    # 头像保存位置
    avatar: F:/Files/avatar/
    # 禁止上传的文件
    not-support-filetype: js,html,htm,shtml,php,css,java,sh,bat,xml
    # 媒体格式
    media-filetype: mp4,avi,mpg,mpeg,wmv,flv,swf,mov,mkv


myapp:
  # MySQL
  db1:
    schema: db_sra_v2
    jdbcUrl: jdbc:mysql://localhost:3306/DB_SRA_V2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  # Redis
  rd1:
    server: localhost:6379
    db: 1
    password:


# Sa-Token 配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 86400
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: random-64
  # 是否输出操作日志
  is-log: false
